pb: "Pedal Board" {
  cbfh: "Dunlop\nCrybaby\nFrom Hell" {}
  polytune3: "TC Electronic\nPolytune 3\nTuner" {}
  rowinng: "Rowin\nNoise Gate" {}
  wec: "Wampler\nEgo\nCompressor" {}
  mc: "Luminite\nGraviton 2\nMIDI controller" {}
  mls: "Oscillator Devices\nHYDRA2E MIDI\nSwitcher" {
    1: "Loop 1" {
      style: {
        stroke-dash: 3
      }
      ts: "JAM\nRattler" {}
    }
    2: "Loop 2" {
      style: {
        stroke-dash: 3
      }
      ts: "JAM\nRed Muck" {}
    }
  }
  ts: "Ibanez\nTube\nScreamer" {}
  cbfh -> polytune3
  cbfh -> rowinng -> mls -> ts
  mc -> mls: "MIDI" {
    style: {
      stroke-dash: 3
    }
  }
  ditto: "TC Electronic\nDitto\nLooper" {}
}

msp: "Mesa Boogie Studio Preamp" {
  A: "Channel A" {}
  B: "Channel B" {}
  Loop: "FX Loop" {}
}
pb.mls -> msp: "Amp Channel\nSwitching" {
  style: {
    stroke-dash: 3
  }
}
pb.ts -> msp
msp.Loop -> pb.wec: "Send" {}
pb.wec -> msp.Loop: "Return" {}

mixer: "Saturnworks\nStereo Mixer" {
  In: "Inputs" {
    A: "Stereo\nChannel A" {}
    B: "Stereo\nChannel B" {}
  }
  Loop: "Stereo\nFX Loop" {}
  Mix: "Mixer" {
    A: "Mix\nOut A" {}
    B: "Mix\nOut B" {}
  }
}
msp.A -> mixer.In.A: "Left"
msp.B -> mixer.In.A: "Right"

mpx1: "Lexicon MPX1 Effects" {
  A: "Channel A" {}
  B: "Channel B" {}
}
pb.mls -> mpx1: "MIDI" {
  style: {
    stroke-dash: 3
  }
}
msp.Loop -> mpx1.A: "Send" {}
mpx1.A -> mixer.In.B: "Left"
mpx1.B -> mixer.In.B: "Right"

m2020: "Mesa Boogie 20:20 Power Amp" {
  A: "Channel A" {}
  B: "Channel B" {}
}
mixer.Mix.A -> m2020.A: "Left"
mixer.Mix.A -> m2020.B: "Right"
mixer.Loop -> pb.ditto: "TRS\nSend"
pb.ditto -> mixer.Loop: "TRS\nReturn"

cab: "Amsterdam\nAmpworks\nSpeaker Cab" {
  A: "Celestion\nG10\nGreenback" {
    shape: "circle"
  }
  B: "Celestion\nG10\nGreenback" {
    shape: "circle"
  }
}
m2020.A -> cab.A: "Left"
m2020.B -> cab.B: "Right"

clarett: "Focusrite\nClarett\n4Pre" {}
mixer.Mix.B -> clarett: "Left"
mixer.Mix.B -> clarett: "Right"

computer: "Computer"
clarett -> computer: "USB-C"

