guitar: "Guitar" {
  shape: "person"
}

pb: "Pedal Board" {
  cbfh: "Dunlop\nCrybaby\nFrom Hell" {}
  polytune3: "TC Electronic\nPolytune 3 Mini\nTuner" {}
  we76c: "Wampler\nEgo 76\nCompressor" {}
  mc: "Luminite\nGraviton 2\nMIDI controller" {}
  mls: "Oscillator Devices\nHYDRA2E\nMIDI Switcher" {
    1: "Loop 1" {
      style: {
        stroke-dash: 3
      }
      ts: "JAM\nRattler" {}
    }
    2: "Loop 2" {
      style: {
        stroke-dash: 3
      }
      ts: "Dr. No Effects\nNecrofuzzicon" {}
    }
  }
  wgt: "Wampler\nGermanium\nTumnus" {}
  cbfh -> polytune3
  cbfh -> we76c -> mls -> wgt
  mc -> mls: "MIDI" {
    style: {
      stroke-dash: 3
    }
  }
  ditto: "TC Electronic\nDitto\nLooper" {}
}
guitar -> pb.cbfh

msp: "Mesa Boogie Studio Preamp" {
  Input: "Input" {}
  A: "Channel A\nOut" {}
  B: "Channel B\nOut" {}
  Loop: "FX Loop" {}
}
pb.mls -> msp: "Amp Channel\nSwitching" {
  style: {
    stroke-dash: 3
  }
}
pb.mls -> msp: "Amp Reverb\nSwitching" {
  style: {
    stroke-dash: 3
  }
}
pb.wgt -> msp.Input

mixer: "Saturnworks\nStereo Mixer" {
  In: "Inputs" {
    A: "Stereo\nChannel A" {}
    B: "Stereo\nChannel B" {}
  }
  Loop: "Stereo\nFX Loop" {}
  Mix: "Mixer" {
    A: "Mix\nOut A" {}
    B: "Mix\nOut B" {}
  }
}
msp.A -> mixer.In.A: "Left"
msp.B -> mixer.In.A: "Right"

jhslbb: "JHS Pedals\nLittle Black\nAmp Box"
rowin: "Rowin\nNoise Gate" {}
ss: "Saturnworks\nSplitter" {}

mpx1: "Lexicon MPX1\nStereo Effects" {
  A: "Channel A" {}
  B: "Channel B" {}
}
pb.mls -> mpx1: "MIDI" {
  style: {
    stroke-dash: 3
  }
}
msp.Loop -> jhslbb: "Send" {}
jhslbb -> rowin -> ss
ss -> msp.Loop: "Return" {}
ss -> mpx1.A: "Split" {}
mpx1.A -> mixer.In.B: "Left"
mpx1.B -> mixer.In.B: "Right"

m2020: "Mesa Boogie\n20:20 Power Amp" {
  A: "Channel A" {}
  B: "Channel B" {}
}
mixer.Mix.A -> m2020.A: "Left"
mixer.Mix.A -> m2020.B: "Right"
mixer.Loop -> pb.ditto: "TRS\nSend"
pb.ditto -> mixer.Loop: "TRS\nReturn"

wsm: "Weber\nStereo Mass\nAttenuator" {
  1: "Channel 1" {}
  2: "Channel 2" {}
}
m2020.A -> wsm.1: "Left"
m2020.B -> wsm.2: "Right"

cab: "Amsterdam\nAmpworks\nSpeaker Cab" {
  A: "Celestion\nG10\nGreenback" {
    shape: "circle"
  }
  B: "Celestion\nG10\nGreenback" {
    shape: "circle"
  }
}
wsm.1 -> cab.A: "Left"
wsm.2 -> cab.B: "Right"

clarett: "Focusrite\nClarett\n4Pre" {}
mixer.Mix.B -> clarett: "Left"
mixer.Mix.B -> clarett: "Right"

computer: "Computer"
clarett -> computer: "USB-C"

