pb: "Pedal Board" {
  cbfh: "Dunlop\nCrybaby\nFrom Hell" {}
  polytune3: "TC\nElectronic\nPolytune 3" {}
  ispdm: "ISP\nDecimate\nNoise Gate" {}
  wec: "Wampler\nEgo\nCompressor" {}
  mc: "Luminite\nGraviton 2\nMIDI controller" {}
  mls: "Oscillator Devices MIDI Loop Switcher" {
    1: "Loop 1" {
      style: {
        stroke-dash: 3
      }
      ts: "JAM\nRattler" {}
    }
    2: "Loop 2" {
      style: {
        stroke-dash: 3
      }
      ts: "Ibanez\nTube Screamer\nMini" {}
    }
  }
  cbfh -> polytune3 -> ispdm -> wec -> mls
  mc -> mls: "MIDI" {
    style: {
      stroke-dash: 3
    }
  }
  ditto: "TC Electronic\nDitto\nLooper" {}
}

msp: "Mesa Boogie Studio Preamp" {
  A: "Channel A" {}
  B: "Channel B" {}
  Loop: "FX Loop" {}
}
pb.mls -> msp: "Amp Channel\nSwitching" {
  style: {
    stroke-dash: 3
  }
}
pb.mls -> msp

mixer: "Saturnworks\nStereo Mixer" {
  In: "Inputs" {
    A: "Stereo\nChannel A" {}
    B: "Stereo\nChannel B" {}
  }
  Loop: "Stereo\nFX Loop" {}
  Mix: "Mixer" {
    A: "Mix\nOut A" {}
    B: "Mix\nOut B" {}
  }
}
msp.A -> mixer.In.A
msp.B -> mixer.In.A

mpx1: "Lexicon MPX1 Effects" {
  A: "Channel A" {}
  B: "Channel B" {}
}
pb.mls -> mpx1: "MIDI" {
  style: {
    stroke-dash: 3
  }
}
msp.Loop -> mpx1.A: "Send" {}
mpx1.A -> mixer.In.B
mpx1.B -> mixer.In.B

m2020: "Mesa Boogie 20:20 Power Amp" {
  A: "Channel A" {}
  B: "Channel B" {}
}
mixer.Mix.A -> m2020.A: "Left"
mixer.Mix.A -> m2020.B: "Right"
mixer.Loop -> pb.ditto: "Send"
pb.ditto -> mixer.Loop: "Return"

cab: "Speaker Cabinet" {
  A: "Celestion\nG10\nGreenback" {
    shape: "circle"
  }
  B: "Celestion\nG10\nGreenback" {
    shape: "circle"
  }
}
m2020.A -> cab.A: "Left"
m2020.B -> cab.B: "Right"

clarett: "Focusrite\nClarett\n4Pre" {}
mixer.Mix.B -> clarett: "Left"
mixer.Mix.B -> clarett: "Right"

computer: "Computer"
clarett -> computer: "USB-C"
